package me.shadaj.scalapy.tensorflow.api.scalaUtils

enum DataType (override private[api] val v: String) extends PythonEnum(v){
  case Float16 extends DataType("float16")
  case Float32 extends DataType("float32")
  case Float64 extends DataType("float64")
  case Bfloat16 extends DataType("bfloat16")
  case Complex64 extends DataType("complex64")
  case Complex128 extends DataType("complex128")
  case Int8 extends DataType("int8")
  case Uint8 extends DataType("uint8")
  case Uint16 extends DataType("uint16")
  case Uint32 extends DataType("uint32")
  case Uint64 extends DataType("uint64")
  case Int16 extends DataType("int16")
  case Int32 extends DataType("int32")
  case Int64 extends DataType("int64")
  case Bool extends DataType("bool")
  case String extends DataType("string")
  case Qint8 extends DataType("qint8")
  case Quint8 extends DataType("quint8")
  case Qint16 extends DataType("qint16")
  case Quint16 extends DataType("quint16")
  case Qint32 extends DataType("qint32")
  case Resource extends DataType("resource")
  case Variant extends DataType("variant")
  case Object extends DataType("object")
}
